[WIP] Calendarを作る
pepabo-mobile-app-training/sunset pull request #16
Opened 2016-09-27 06:37 UTC by rhythnn

### 概要
キー機能の1つであるカレンダーを作成します

### 内容
- [ ] 機能作成
  - Storyboard
  - view controller
  - model, helper
- [ ] テストを書く
  - 単体テスト
  - UIテスト

2016-09-27 09:18 UTC, rhythnn commented
### 6s
![simulator screen shot 2016 09 27 18 16 28](https://cloud.githubusercontent.com/assets/13099942/18867345/ceebe87a-84de-11e6-9302-1dbfa075668f.png)

2016-09-27 09:19 UTC, rhythnn commented
### 7 plus
![simulator screen shot 2016 09 27 18 14 51](https://cloud.githubusercontent.com/assets/13099942/18867360/dcf1160c-84de-11e6-9a60-81ea02c189fc.png)

2016-09-27 09:19 UTC, rhythnn commented
## SE
![simulator screen shot 2016 09 27 18 15 46](https://cloud.githubusercontent.com/assets/13099942/18867367/e7d9a61a-84de-11e6-83d4-b288448615d6.png)

2016-09-28 02:33 UTC, Asuforce requested changes

2016-09-28 02:33 UTC, Asuforce commented on sunsetUITests/sunsetUITests.swift
> +
空行除去お願いします

2016-09-28 02:33 UTC, Asuforce commented on sunsetTests/sunsetTests.swift
> +
空行除去お願いします

2016-09-28 02:33 UTC, Asuforce commented on sunsetTests/sunsetTests.swift
>          // Use XCTAssert and related functions to verify your tests produce the correct results.
ここ二行のコメント不要です

2016-09-28 02:33 UTC, Asuforce commented on sunsetTests/sunsetTests.swift
> +
空行除去お願いします

2016-09-28 02:33 UTC, Asuforce commented on sunset/Classes/Models/DateManager.swift
> +import UIKit
空行を除去して上に詰めて下さい

2016-09-28 02:33 UTC, Asuforce commented on sunset/Classes/Models/DateManager.swift
> +
空行を除去してください

2016-09-28 02:33 UTC, Asuforce commented on sunset/Classes/Controllers/CalendarViewController.swift
> +
空行を除去してください

2016-09-28 02:33 UTC, Asuforce commented on sunset/Classes/Controllers/CalendarViewController.swift
> +
空行を除去してください

2016-09-28 02:33 UTC, Asuforce commented on sunset/Classes/Controllers/CalendarViewController.swift
> +import UIKit
上三行を削除して詰めて下さい

2016-09-28 02:59 UTC, Asuforce approved these changes

2016-09-28 03:00 UTC, rhythnn commented on sunsetUITests/sunsetUITests.swift
> +
ありがとう:sparkles:

2016-09-28 03:00 UTC, Asuforce commented
LGTM
WIP外してくだされ〜

2016-09-28 03:03 UTC, merged